---
- include: infra.yml
- include: idm.yml
- name: Configure host dns
  hosts: kvmhosts
  become: yes
  roles:
    - configure-host

- include: generic.yml
  vars_prompt:
    - name: "rhn_activationkey"
      prompt: "Please enter your activationkey"
    - name: "rhn_orgid"
      prompt: "Please enter your orgid"
      default: "5318211"

- name: "Install generic node"
  hosts: kvmhosts
  roles:
    - role: deploy-vm-generic
      vm_name: changeme
      vm_hostname: '{{ vm_name }}.{{ dns_name }}'
      vm_mem_size: '2048'
      vm_mem_size_max: '2048'
      vm_disk_size: '10'
      vm_num_cpus: '2'
      vm_num_cpus_max: '4'
      vm_memory_options: "--memory={{ vm_mem_size }},maxmemory={{ vm_mem_size_max }} --memballoon virtio"
  roles:
    - common
    - common-client

##- name: Deploy Red Hat Satellite virtual machine
#  hosts: kvmhosts
#  become: yes
#  roles:
#
#- name: Configure SAT
#  hosts: satserver
#  become: yes
#  roles:
#    - configure-sat
