---
- name: Deploy, configure kvm, and deploy VMs.
  hosts: kvmhosts
  become: yes

  roles:
    - deploy-infra
    - deploy-vm-idm

- name: Configure IDM
  hosts: idmserver
  become: yes
  become_user: root

  roles:
    - configure-idm
