---
- hosts: kvmhosts
  become: yes
  roles:
    - deploy-infra
    - deploy-vms

- hosts: vm:childrens
  roles:
    - role: common
    - role: common-client

- hosts: idmserver
- hosts: satserver
- hosts: towerserver
