- name: "Install {{ vm_name }}"
  hosts: kvmhosts
  roles:
    - role: deploy-vm-generic
      vm_name: changeme
      vm_hostname: '{{ vm_name }}.{{ dns_name }}'
      vm_mem_size: '2048'
      vm_mem_size_max: '2048'
      vm_disk_size: '10'
      vm_num_cpus: '2'
      vm_num_cpus_max: '4'
      vm_memory_options: "--memory={{ vm_mem_size }},maxmemory={{ vm_mem_size_max }} --memballoon virtio"
      int_vm_generic_mac: 'ba:dc:0f:0f:ef:8f'
      int_vm_generic_ip: '172.32.0.251'
- name: "Configure {{ vm_name }}"
  hosts: generic
  roles:
    - role: common
    - role: common-client
