---
- name: DEPLOY KVM | PRE - checking if hardware virtualization is supported
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: hw_check
  tags:
    - pre-check

- name: DEPLOY KVM | PRE - fail if hardware virtualization not supported
  fail: msg="Hardware Virtualization Not Supported on this platform!!!!"
  when: hw_check.stdout == "0"
  tags:
    - pre-check

- name: DEPLOY KVM | Installing packages
  yum: name="{{ item }}" state=latest
  with_items: "{{ libvirt_packages }}"

- name: DEPLOY KVM | Enabling and starting libvirtd service
  service:
    name=libvirtd
    state=started
    enabled=yes
  tags:
    - deploy-kvm

- name: DEPLOY KVM NETWORK | Creating internal network
  virt_net:
    command=define
    name="{{ internal_network_name }}"
    xml='{{ lookup("template", "../templates/internal.xml.j2") }}'
    autostart=yes
  tags:
    - network

- name: DEPLOY KVM NETWORK | Starting internal network
  virt_net:
    name="{{ internal_network_name }}"
    state=active
  tags:
    - network

- name: DEPLOY KVM NETWORK | Creating external network
  virt_net:
    command=define
    name="{{ external_network_name }}"
    xml='{{ lookup("template", "../templates/external.xml.j2") }}'
    autostart=yes
  tags:
    - network

- name: DEPLOY KVM NETWORK | Starting external network
  virt_net:
    name="{{ external_network_name }}"
    state=active
  tags:
    - network

- name: DEPLOY KVM STORAGE | Creating Vm directory
  file:
    path='{{ storage_pool_location }}'
    state=directory mode=0755
  tags:
    - storage

- name: DEPLOY KVM STORAGE | Creating VM spool
  virt_pool:
    command=define
    name="{{ storage_name }}"
    xml='{{ lookup("template", "../templates/storage.xml.j2") }}'
  tags:
    - storage

- name: DEPLOY KVM STORAGE | Starting VM spool
  virt_pool:
    name="{{ storage_name }}"
    state=active
  tags:
    - storage
