---
- name: DEPLOY INFRA | PRE - checking if hardware virtualization is supported
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  register: hw_check

- name: DEPLOY INFRA | PRE - fail if hardware virtualization not supported
  fail: msg="Hardware Virtualization Not Supported on this platform!!!!"
  when: hw_check.stdout == "0"

- name: DEPLOY INFRA | Add nested virtualization
  modprobe:
    name: kvm-intel
    state: present
    params: "nested=1,enable_shadow_vmcs=1,enable_apicv=1,ept=1"

- name: DEPLOY INFRA | Installing packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ libvirt_packages }}"

- name: DEPLOY INFRA | Enabling and starting libvirtd service
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: DEPLOY NETWORKS | create
  virt_net:
    command: define
    name: "{{ item }}"
    xml: '{{ lookup("template", "templates/{{ item }}.xml.j2") }}'
    autostart: yes
  with_items: "{{ infra_networks }}"

- name: DEPLOY NETWORKS | start
  virt_net:
    name: "{{ item }}"
    state: active
  with_items: "{{ infra_networks }}"

- name: DEPLOY INFRA STORAGE | Creating Vm directory
  file:
    path: /var/lib/libvirt/images/{{ storage_name }}
    state: directory
    mode: 0755

- name: DEPLOY INFRA STORAGE | Creating VM pool
  virt_pool:
    command: define
    name: "{{ storage_name }}"
    xml: '{{ lookup("template", "../templates/storage.xml.j2") }}'

- name: DEPLOY INFRA STORAGE | Starting VM pool
  virt_pool:
    command: create
    name: "{{ storage_name }}"
