---
- name: Destroy VMs
  virt: name={{ item }}.{{ dns_name }} command=destroy
  with_items:
  - "{{ idm_name }}"
  - "{{ sat_name }}"
  - "{{ tower_name }}"
  ignore_errors: True

- name: Undefine VMs
  virt: name={{ item }}.{{ dns_name }} command=undefine
  with_items:
  - "{{ idm_name }}"
  - "{{ sat_name }}"
  - "{{ tower_name }}"
  ignore_errors: True

- name: Remove networks
  virt_net: name={{ item }} state=absent
  with_items:
  - "{{ internal_network_name }}"
  - "{{ external_network_name }}"
  ignore_errors: True

- name: Remove storage
  virt_pool:
    command: delete
    name: "{{ storage_name }}"
  ignore_errors: True
