---
- name: Destroy VMs
  virt: name={{ item }}.{{ dns_name }} command=destroy
  with_items:
  - "{{ idm_name }}"
  - "{{ sat_name }}"
  - "{{ tower_name }}"
  - "changeme"
#{{ dns_name }}
  ignore_errors: True

- name: Undefine VMs
  virt: name={{ item }}.{{ dns_name }} command=undefine
  with_items:
  - "{{ idm_name }}"
  - "{{ sat_name }}"
  - "{{ tower_name }}"
  - "changeme"
  ignore_errors: True

- name: Remove networks
  virt_net: name={{ item }} state=absent
  with_items:
  - "{{ internal_network_name }}"
  - "{{ external_network_name }}"
  ignore_errors: True

- name: Stop storage pool
  virt_pool:
    command: stop
    name: "{{ storage_name }}"
  ignore_errors: True

- name: Find disks in storage pool
  find: path={{ storage_pool_location }} file_type=file
  register: files

- name: print list of files
  file: state=absent path={{ item.path }}
  with_items:
  - "{{ files.files }}"

#  debug:
#    msg: "{{ files }}"

- name: Delete storage pool
  virt_pool:
    state: deleted
    name: "{{ storage_name }}"
  ignore_errors: True

- name: CLEANUP - Remove dns fix.
  file: path=/etc/NetworkManager/dnsmasq.d/{{ dns_name }}.conf state=absent
  notify:
    - reload Network Manager

# FIXME : find a way to keep the permission on the file.
#- name: Cleanup known hosts file
#  known_hosts:
#    path: ~/.ssh/known_hosts
#    name: 192.168.200.254
#    state: absent
#    with_items:
#    - "{{ 192.168.200.254 }}"
