---
- name: CONFIGURE IDM | Set the hostname
  hostname: name={{ ansible_fqdn }}

- name: CONFIGURE IDM | Subscribe the system to RHN
  redhat_subscription: state=present username={{ rhn_username }} password={{ rhn_password }} pool='^(Red Hat Enterprise Linux Self-Supported|Red Hat Satellite Employee Subscription)$'

- name: CONFIGURE IDM | Disable all the repos.
  command: subscription-manager repos --disable="*"

- name: CONFIGURE IDM | Enable the appropriate repos.
  command: subscription-manager repos --enable={{ item }}
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-rh-common-rpms
    - rhel-7-server-optional-rpms

- name: CONFIGURE IDM | Setup the firewall
  firewalld: service={{ item }} permanent=true state=enabled immediate=true
  with_items:
     - freeipa-ldap
     - https
     - http
     - ldaps
     - ldap
     - kerberos
     - kpasswd
     - dns
     - ntp
    notify:
        - restart firewalld

- name: CONFIGURE IDM | Configure ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: CONFIGURE IDM | Configure {{ ansible_fqdn }} as a router
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled
    zone: public

- name: CONFIGURE IDM | Setup IDM
  command: ipa-server-install
    --hostname {{ ansible_fqdn }}
    --ip-address {{ ext_idm_ip }}
    --ip-address {{ int_idm_ip }}
    --domain {{ dns_name }}
    --realm {{ dns_name  | upper }}
    --setup-dns
    --reverse-zone {{ int_net_rev }}.in-addr.arpa.
    --reverse-zone {{ ext_net_rev }}.in-addr.arpa.
    --allow-zone-overlap
    --forwarder {{ kvm_host_ip }}
    --idstart 1000
    --idmax 65535
    --mkhomedir
    -a {{ ipaserver_admin_password }}
    -p {{ ipaserver_dir_admin_password }}
    -U

- name: CONFIGURE IDM | Update all packages.
  yum:
    name: '*'
    state: latest

