---
- name: CONFIGURE IDM | Set the hostname
  hostname: name={{ ansible_fqdn }}

- name: CONFIGURE IDM | Setup the firewall
  firewalld: service={{ item }} permanent=true state=enabled immediate=true
  with_items:
     - freeipa-ldap
     - https
     - http
     - ldaps
     - ldap
     - kerberos
     - kpasswd
     - dns
     - ntp
     - ssh
  notify:
    - restart firewalld

- name: CONFIGURE IDM | Configure ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: CONFIGURE IDM | Deactivate ipv6 - 1
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: CONFIGURE IDM | Deactivate ipv6 - 2
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: CONFIGURE IDM | Configure {{ ansible_fqdn }} as a router
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled
    zone: public

- name: CONFIGURE IDM | Setup IDM
  command: ipa-server-install
    --hostname {{ ansible_fqdn }}
    --ip-address {{ int_idm_ip }}
    --domain {{ dns_name }}
    --realm {{ dns_name  | upper }}
    --setup-dns
    --reverse-zone {{ int_net_rev }}.in-addr.arpa.
    --allow-zone-overlap
    --forwarder {{ kvm_host_ip }}
    --idstart 1000
    --idmax 65535
    --mkhomedir
    -a {{ ipaserver_admin_password }}
    -p {{ ipaserver_dir_admin_password }}
    --no-dnssec-validation
    --unattended

- name: CONFIGURE IDM | Update all packages.
  yum:
    name: '*'
    state: latest

