---
- name: COMMON CLIENT - Register into IDM.
  command: ipa-client-install -w {{ ipaserver_admin_password }} -U --enable-dns-updates --domain={{ dns_name }} --mkhomedir --realm {{ dns_name  | upper }} --server={{ idm_name }} -N --unattended

# open ports : ssh / ntp
# register in RHN
# register in IDM
