---
galaxy_info:
  author: William Hoffmann
  description:
  company: Red Hat France
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - system
dependencies: []
