---
ipa_name: srv
vm_name: '{{ ipa_name }}'
vm_hostname: '{{ vm_name }}.{{ dns_name }}'
vm_mem_size: '2048'
vm_mem_size_max: '2048'
vm_disk_size: '10'
vm_num_cpus: '2'
vm_num_cpus_max: '4'

vm_memory_options: "--memory={{ vm_mem_size }},maxmemory={{ vm_mem_size_max }} --memballoon virtio"

keyboard: 'us'
lang: 'en_US'
timezone: 'Europe/Paris'

ks_repo:
  EL:
    7: ftp://{{ kvm_host_ip }}/pub/EL7
