---
- name: CONFIGURE | Set the hostname
  hostname: name={{ ansible_fqdn }}

- name: CONFIGURE | Subscribe the system to RHN
  redhat_subscription: state=present activationkey={{ rhn_activationkey }} org_id={{ rhn_orgid }}

- name: CONFIGURE | Disable all the repos.
  command: subscription-manager repos --disable="*"

- name: CONFIGURE | Enable the appropriate repos.
  command: subscription-manager repos --enable={{ item }}
  with_items:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-rh-common-rpms
    - rhel-7-server-optional-rpms

- name: CONFIGURE | Setup the firewall
  firewalld: service={{ item }} permanent=true state=enabled immediate=true
  with_items:
     - ssh
     - ntp
  notify:
    - restart firewalld
