---

- debug: msg="vm_name "{{ vm_name }}""

- name: DEPLOY KVM VM | Get template
  get_url:
    url: ftp://localhost/pub/template.qcow2
    checksum: "{{ libvirt_image_sha256 }}"
    dest: "{{ storage_pool_location }}/{{ vm_name }}.qcow2"


- name: DEPLOY KVM VM | Define VM
  virt:
    name="{{ vm_name }}"
    command=define
    xml='{{ lookup("template", "../templates/template-vm.xml.j2") }}'
    uri=qemu:///system

- name: DEPLOY KVM VM | Start vm
  virt:
    name="{{ vm_name }}"
    state=running
    uri=qemu:///system

