---
- name: DEPLOY KVM VM | Get template
  get_url:
    url: ftp://localhost/pub/template.qcow2
    checksum: "{{ libvirt_image_sha256 }}"
    dest: "{{ storage_pool_location }}/srv.{{ dns_name }}.qcow2"

- name: DEPLOY KVM VM | Define ipa VM
  virt:
    name=srv.{{ dns_name }}
    command=define
    xml='{{ lookup("template", "../templates/template-ipa.xml.j2") }}'
    uri=qemu:///system

- name: DEPLOY KVM VM | Start ipa vm
  virt:
    name=srv.{{ dns_name }}
    state=running
    uri=qemu:///system

